### ISSUE TITLE
The responsive props object doesn't provide a "default" breakpoint for devices smaller than sm

### ISSUE THREAD

**Issue by MD-MOUAD** [brijr/craft#3]
In the Box component, when defining responsive props such as direction, wrap, gap, cols, or rows, the code currently expects breakpoints (sm, md, etc.). However, if you don't explicitly provide a value for the smallest screen size like mobile, the component may not render properly or be responsive on smaller devices.

**Comment by brijr** [comment]
https://github.com/brijr/craft/pull/4 

Thanks @MD-MOUAD
